### ISSUE TITLE
missing build PEP-491

### ISSUE THREAD

**Issue by juyoung-yoo** [pex-tool/pex#1091] opened 2020-10-27 06:41 UTC
1. I try `pex -o env.pex -vv --wheel dist/scripts-0.1.1-py3-none-any.whl -i [private pypi repository]` 

```
$`pex -o env.pex -vv --wheel dist/scripts-0.1.1-py3-none-any.whl -i [private pypi repository]` 
pex:   Resolving distributions (['dist/scripts-0.1.1-py3-none-any.whl']): 12239.9ms
pex:     Resolving for:
  DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.7', PythonIdentity('/usr/bin/python3', 'cp37', 'cp37m', 'manylinux2014_x86_64', (3, 7, 9)))): 9740.0ms
pex:     Building distributions for:
  BuildRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.7', PythonIdentity('/usr/bin/python3', 'cp37', 'cp37m', 'manylinux2014_x86_64', (3, 7, 9)))), source_path='/tmp/tmpsh9s_5zd/usr.bin.python3.7/psutil-5.7.3.tar.gz', fingerprint='0b093faed351cf89e930d1c3ba380831b068ebc1')
  BuildRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.7', PythonIdentity('/usr/bin/python3', 'cp37', 'cp37m', 'manylinux2014_x86_64', (3, 7, 9)))), source_path='/tmp/tmpsh9s_5zd/usr.bin.python3.7/bs4-0.0.1.tar.gz', fingerprint='b309d9b50489cc64263d11491e6a19c29c3a484d'): 2.5ms
pex:     Installing:
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.7', PythonIdentity('/usr/bin/python3', 'cp37', 'cp37m', 'manylinux2014_x86_64', (3, 7, 9)))), wheel_path='/tmp/tmpsh9s_5zd/usr.bin.python3.7/soupsieve-2.0.1-py3-none-any.whl', fingerprint='9b247ae42ab62881ba17f5b7a181308e29bf28c7')
....
**wheel_path='/tmp/tmpsh9s_5zd/usr.bin.python3.7/xxxcommon-0.0.2-py3-none-any.whl', fingerprint='36f08ba0010a8e4879b612e53d661a6743f8560f')**
...
```

2. success and enter env.pex 

```bash
$./env.pex 
$ import sys
$ sys.path 
['/app/env.pex', '/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/root/.pex/installed_wheels/7cd5856dbec587be19faa3eece41bb5ff5e28550/beautifulsoup4-4.9.3-py3-none-any.whl', '/root/.pex/installed_wheels/9b247ae42ab62881ba17f5b7a181308e29bf28c7/soupsieve-2.0.1-py3-none-any.whl', '/root/.pex/installed_wheels/52e5a58c0d4c49d87e1561e05140cfbf70603fdd/bs4-0.0.1-py3-none-any.whl', '/root/.pex/installed_wheels/f37eb16dd168e81f95c31495516aa948e7b846ee/certifi-2020.6.20-py2.py3-none-any.whl', '/root/.pex/installed_wheels/96faab7de7e9a71b37f22adb64daf2898e967e3e/chardet-3.0.4-py2.py3-none-any.whl', '/root/.pex/installed_wheels/999b6718b4d789d8ca0d2ddf7c07826154291825/idna-2.10-py2.py3-none-any.whl', '/root/.pex/installed_wheels/860a0cfe68e6a86b931f0e59ed5fddba2d812c0f/joblib-0.17.0-py3-none-any.whl', '/root/.pex/installed_wheels/c1761ac0eb0a7e44d975174618fffa2fe0d5edd8/numpy-1.19.2-cp37-cp37m-manylinux2010_x86_64.whl', '/root/.pex/installed_wheels/c4b2f95b7858578194b760ecf33264c1dbe02c74/pandas-1.1.3-cp37-cp37m-manylinux1_x86_64.whl', '/root/.pex/installed_wheels/bf0bf128eb236e40fbe316ca57babd8c483e93ea/pytz-2020.1-py2.py3-none-any.whl', '/root/.pex/installed_wheels/3005ff67df93ee276fb8631e17c677df852254ad/python_dateutil-2.8.1-py2.py3-none-any.whl', '/root/.pex/installed_wheels/8730d16507db66e828c696ecc7cb785e557900bb/six-1.15.0-py2.py3-none-any.whl', '/root/.pex/installed_wheels/957bead8a8ab11a08532503a8b14bc41ab5b2664/psutil-5.7.3-cp37-cp37m-linux_x86_64.whl', '/root/.pex/installed_wheels/79e063e4fd8bbb986080c1cd17968ce8c1afb15b/pybind11-2.6.0-py2.py3-none-any.whl', '/root/.pex/installed_wheels/12d6bdcbe7475c7374984931b6e27c4bcfc360a8/pycryptodome-3.9.8-cp37-cp37m-manylinux1_x86_64.whl', '/root/.pex/installed_wheels/e8cb9b8598a2d6f3b4190e6425ccbd93827b142d/pyorc-0.3.0-cp37-cp37m-manylinux2010_x86_64.whl', '/root/.pex/installed_wheels/1ee1d4eb7c910502b93f61156af26178a5e747c7/requests-2.24.0-py2.py3-none-any.whl', '/root/.pex/installed_wheels/8da829e6ad282e04cfa21a7228ab988ceaec0d4e/urllib3-1.25.11-py2.py3-none-any.whl', '/root/.pex/installed_wheels/df339d4610c67bd01e4d69989f5599eba19ca5d8/scikit_learn-0.23.2-cp37-cp37m-manylinux1_x86_64.whl', '/root/.pex/installed_wheels/75b6195d940ac23af2256bc7d86274d59652c675/scipy-1.5.3-cp37-cp37m-manylinux1_x86_64.whl', '/root/.pex/installed_wheels/9910c9618380acc6191856cef411f0049bbab932/threadpoolctl-2.1.0-py3-none-any.whl', '/root/.pex/installed_wheels/39d79d315f3130bededd32fa039ac94991c06e3e/soynlp-0.0.493-py3-none-any.whl', '/app/env.pex/.bootstrap']
```

Some libraries are missing. especially **xxxcommon-0.0.2-py3-none-any.whl**
Some libraries are [PEP-491](https://www.python.org/dev/peps/pep-0491/) wheel file. 

---

I wonder if pex use `top-level` and `.egg` file for building.
I want to wheel(PEX491) build!

**Comment by jsirois** [comment] 2020-11-06 21:41
@juyoung-yoo there is not enough information here to help debug.Is there any way you can provide an open-source example to reproduce the issue with?

Also note that you need not specify `--wheel` - that is the default.

Nominally, the form of PEX creation you use here does work:
```
$ pip download --dest /tmp/wheels requests
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
  Saved /tmp/wheels/requests-2.24.0-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
  Saved /tmp/wheels/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
  Saved /tmp/wheels/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
  Saved /tmp/wheels/certifi-2020.6.20-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
  Saved /tmp/wheels/urllib3-1.25.11-py2.py3-none-any.whl
Successfully downloaded requests chardet idna certifi urllib3
$ cp /tmp/wheels/requests-2.24.0-py2.py3-none-any.whl .
$ pex -o env.pex -vv --wheel ./requests-2.24.0-py2.py3-none-any.whl 
pex: Building pex :: Resolving distributions (['./requests-2.24.0-py2.py3-none-any.whl']) :: Resolving for:
pex: Hashing pex                                                                                                                                                                                                                                                                              pex: Hashing pex: 29.5ms
pex: Isolating pex: 0.1ms
pex: PEX.run invoking /usr/bin/python3.8 /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f --disable-pip-version-check --no-python-version-warning --exists-action a --isolated -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmpu8v1yzcp/usr.bin.python3.8 ./requests-2.24.0-py2.py3-none-any.whl --header Cache-Control:max-age=3600 --retries 5 --timeout 15
pex: Found site-library: /usr/lib/python3.8/site-packages
pex: Not a tainted path element: /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.bootstrap
pex: Not a tainted path element: /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f
pex: Not a tainted path element: /usr/lib/python38.zip
pex: Not a tainted path element: /usr/lib/python3.8
pex: Not a tainted path element: /usr/lib/python3.8/lib-dynload
pex: Not a tainted path element: /home/jsirois/.local/lib/python3.8/site-packages
pex: Tainted path element: /usr/lib/python3.8/site-packages
pex: Scrubbing from user site: /home/jsirois/.local/lib/python3.8/site-packages
pex: Scrubbing from site-packages: /usr/lib/python3.8/site-packages
pex: New sys.path: ['/home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.bootstrap', '/home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload']
pex: Activating PEX virtual environment from /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f: 8.7ms                                                                                                                              
pex:   Searching dependency cache: /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.deps: 0.8ms
pex:     Adding setuptools 42.0.2: 0.0ms
pex:     Adding wheel 0.33.6: 0.0ms
pex:     Adding pip 20.0.dev0: 0.0ms
pex:   Resolving pip from [Requirement.parse('pip==20.0.dev0')]: 1.7ms
pex:   Resolving setuptools from [Requirement.parse('setuptools==42.0.2')]: 2.3ms
pex:   Resolving wheel from [Requirement.parse('wheel==0.33.6')]: 1.8ms
pex:   Activating pip 20.0.dev0: 0.2ms
pex:     Adding sitedir: 0.1ms
pex:   Activating setuptools 42.0.2: 0.2ms
pex:     Adding sitedir: 0.1ms
pex:   Activating wheel 0.33.6: 0.2ms
pex:     Adding sitedir: 0.1ms
pex: Bootstrap complete, performing final sys.path modifications...
pex: Demoting code from Bootstrap(sys_path_entry='/home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.bootstrap')
pex: PYTHONPATH contains:
pex:     /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f
pex:   * /usr/lib/python38.zip
pex:     /usr/lib/python3.8
pex:     /usr/lib/python3.8/lib-dynload
pex:     /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.deps/pip
pex:     /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.deps/setuptools
pex:     /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.deps/wheel
pex:     /home/jsirois/.pex/pip.pex/6cc8c105ac55188329eb3c712c0c3a549940348f/.bootstrap
pex:   * - paths that do not exist or will be imported via zipimport
pex: Building pex :: Resolving distributions (['./requests-2.24.0-py2.py3-none-any.whl']) :: Installing:
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/urllib3-1.25.11-py2.py3-none-any.whl', fingerprint='8da829e6ad282e04cfa21a7228ab988ceaec0d4e')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/idna-2.10-py2.py3-none-any.whl', fingerprint='999b6718b4d789d8ca0d2ddf7c07826154291825')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/certifi-2020.6.20-py2.py3-none-any.whl', fingerprint='f37eb16dd168e81f95c31495516aa948e7b846ee')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/chardet-3.0.4-py2.py3-none-any.whl', fingerprint='96faab7de7e9a71b37f22adb64daf2898e967e3e')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/requests-2.24.0-py2.py3-none-any.whlpex: Using cached installation of urllib3-1.25.11-py2.py3-none-any.whl at /home/jsirois/.pex/installed_wheels/8da829e6ad282e04cfa21a7228ab988ceaec0d4e/urllib3-1.25.11-py2.py3-none-any.whl                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
pex: Using cached installation of idna-2.10-py2.py3-none-any.whl at /home/jsirois/.pex/installed_wheels/999b6718b4d789d8ca0d2ddf7c07826154291825/idna-2.10-py2.py3-none-any.whl
pex: Using cached installation of certifi-2020.6.20-py2.py3-none-any.whl at /home/jsirois/.pex/installed_wheels/f37eb16dd168e81f95c31495516aa948e7b846ee/certifi-2020.6.20-py2.py3-none-any.whl
pex: Using cached installation of chardet-3.0.4-py2.py3-none-any.whl at /home/jsirois/.pex/installed_wheels/96faab7de7e9a71b37f22adb64daf2898e967e3e/chardet-3.0.4-py2.py3-none-any.whl
pex: Using cached installation of requests-2.24.0-py2.py3-none-any.whl at /home/jsirois/.pex/installed_wheels/1ee1d4eb7c910502b93f61156af26178a5e747c7/requests-2.24.0-py2.py3-none-any.whl
pex: Building pex :: Resolving distributions (['./requests-2.24.0-py2.py3-none-any.whl']) :: Calculating installed requirements for:
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[urllib3 1.25.11 (/home/jsirois/.pex/installed_wheels/8da829e6ad282e04cfa21a7228ab988ceaec0d4e/urllib3-1.25.11-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[idna 2.10 (/home/jsirois/.pex/installed_wheels/999b6718b4d789d8ca0d2ddf7c07826154291825/idna-2.10-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[certifi 2020.6.20 (/home/jsirois/.pex/installed_wheels/f37eb16dd168e81f95c31495516aa948e7b846ee/certifi-2020.6.20-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[chardet 3.0.4 (/home/jsirois/.pex/installed_wheels/96faab7de7e9a71b37f22adb64daf2898e967e3e/chardet-3.0.4-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[requests 2.24.0 (/home/jsirois/.pex/installed_wheels/1ee1d4eb7c910502b93f61  urllib3==1.25.11; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version != "3.4.*" and python_version < "4" and python_version >= "2.7" -> urllib3 1.25.11
  idna==2.10; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7" -> idna 2.10
  certifi==2020.6.20 -> certifi 2020.6.20
  chardet==3.0.4 -> chardet 3.0.4
  requests==2.24.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version != "3.4.*" and python_version >= "2.7" -> requests 2.24.0
pex: Building pex: 835.8ms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
pex:   Resolving distributions (['./requests-2.24.0-py2.py3-none-any.whl']): 835.3ms
pex:     Resolving for:
  DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))): 542.8ms
pex:     Installing:
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/urllib3-1.25.11-py2.py3-none-any.whl', fingerprint='8da829e6ad282e04cfa21a7228ab988ceaec0d4e')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/idna-2.10-py2.py3-none-any.whl', fingerprint='999b6718b4d789d8ca0d2ddf7c07826154291825')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/certifi-2020.6.20-py2.py3-none-any.whl', fingerprint='f37eb16dd168e81f95c31495516aa948e7b846ee')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/chardet-3.0.4-py2.py3-none-any.whl', fingerprint='96faab7de7e9a71b37f22adb64daf2898e967e3e')
  InstallRequest(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), wheel_path='/tmp/tmpu8v1yzcp/usr.bin.python3.8/requests-2.24.0-py2.py3-none-any.whl', fingerprint='1ee1d4eb7c910502b93f61156af26178a5e747c7'): 8.6ms
pex:     Calculating installed requirements for:
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[urllib3 1.25.11 (/home/jsirois/.pex/installed_wheels/8da829e6ad282e04cfa21a7228ab988ceaec0d4e/urllib3-1.25.11-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[idna 2.10 (/home/jsirois/.pex/installed_wheels/999b6718b4d789d8ca0d2ddf7c07826154291825/idna-2.10-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[certifi 2020.6.20 (/home/jsirois/.pex/installed_wheels/f37eb16dd168e81f95c31495516aa948e7b846ee/certifi-2020.6.20-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[chardet 3.0.4 (/home/jsirois/.pex/installed_wheels/96faab7de7e9a71b37f22adb64daf2898e967e3e/chardet-3.0.4-py2.py3-none-any.whl)])
  Request(target=DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/home/jsirois/.venv/pex/bin/python3', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 6)))), distributions=[requests 2.24.0 (/home/jsirois/.pex/installed_wheels/1ee1d4eb7c910502b93f61156af26178a5e747c7/requests-2.24.0-py2.py3-none-any.whl)]): 222.2ms
Saving PEX file to env.pex
$ ./env.pex 
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import sys
>>> print("\n".join(sys.path))
/home/jsirois/env.pex
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/jsirois/.pex/installed_wheels/f37eb16dd168e81f95c31495516aa948e7b846ee/certifi-2020.6.20-py2.py3-none-any.whl
/home/jsirois/.pex/installed_wheels/96faab7de7e9a71b37f22adb64daf2898e967e3e/chardet-3.0.4-py2.py3-none-any.whl
/home/jsirois/.pex/installed_wheels/999b6718b4d789d8ca0d2ddf7c07826154291825/idna-2.10-py2.py3-none-any.whl
/home/jsirois/.pex/installed_wheels/1ee1d4eb7c910502b93f61156af26178a5e747c7/requests-2.24.0-py2.py3-none-any.whl
/home/jsirois/.pex/installed_wheels/8da829e6ad282e04cfa21a7228ab988ceaec0d4e/urllib3-1.25.11-py2.py3-none-any.whl
/home/jsirois/env.pex/.bootstrap
>>> 
```
So the error will be in some detail and more detail is needed from the example to track down the issue.

**Comment by jsirois** [comment] 2024-08-14 18:29
@juyoung-yoo as demonstrated, Pex does allow you to build a PEX from wheels (PEP-491 as you say) directly. Since you have not followed up with more details, I'm going to close this issue. If you can provide more details though, please re-open with those details.

**Closed by jsirois** 2024-08-14 18:29 UTC
Labels: question
